config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  # Routes only without session
  scope constraints: ->(req) { req.session[:user_id].blank? } do
    get 'login', to: 'sessions#new', as: :new_login
    post 'login', to: 'sessions#create', as: :login
    resources :registration, only: [:new, :create]
  end

  # Routes only with session
  scope constraints: ->(req) { !req.session[:user_id].blank? } do
    # For every role
    get 'logout', to: 'sessions#destroy', as: :logout
    resources :purchase_orders

    # Just if you are an admin
    scope constraints: ->(req) { req.session[:role] == 'admin' } do
      resources :users, only: [:index, :new, :create, :destroy]
    end

    # Just if you are a regular_user
    scope constraints: ->(req) { req.session[:role] == 'regular_user' } do
    end


  end

  # For everyone
  # STATIC PAGES
  get 'contact_us', to: "welcome#contact_us", as: :contact_us
  resources :announcements
  resources :documents
  post 'create_document', to: 'documents#create', as: :create_document
  resources :reports do
    collection do
      get 'invoices'
      get 'deliveries'
      get 'product_information'
      get 'product_statistics'
      get 'purchase_orders'
      get 'product_summary'
      get 'date_statistics'
      get 'product_catalog'
      get 'product_documents'
      get 'invoices_json'
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  email         :string(255)
#  name          :string(255)
#  last_name     :string(255)
#  username      :string(255)
#  password_hash :string(255)
#  password_salt :string(255)
#  role_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  deleted_at    :datetime
#  customer_id   :integer
#

class User < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :role, inverse_of: :users
  belongs_to :customer, inverse_of: :users

  validates :role, presence: true
  validates :name, presence: true
  validates :last_name, presence: true
  validates :password_hash, presence: true, on: :update
  validates :password_salt, presence: true, on: :update
  validates :password, presence: true, on: :create,
                       length: { in: 8..20 }
  validates :password_confirmation, presence: true, on: :create
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: true, scope: :deleted_at }
  validates :username, presence: true, uniqueness: { case_sensitive: true,
                                                     scope: :deleted_at }
  validate :valid_confirmation?, on: :create

  attr_accessor :password
  attr_accessor :password_confirmation

  before_create :encrypt

  after_create :assign_customer_if_admin

  def full_name
    "#{name} #{last_name}"
  end

  def admin?
    role.name == 'admin'
  end

  def regular_user?
    role.name == 'regular_user'
  end

  private

  def encrypt
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def valid_confirmation?
    valid = password == password_confirmation
    errors.add(:password_confirmation, 'wrong confirmation') unless valid
    valid
  end

  def assign_customer_if_admin
    update(customer_id: 1) if admin?
  end

end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  email         :string(255)
#  name          :string(255)
#  last_name     :string(255)
#  username      :string(255)
#  password_hash :string(255)
#  password_salt :string(255)
#  role_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  deleted_at    :datetime
#  customer_id   :integer
#

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all.includes(:role)
  end

  def create
    @user = User.new(object_params)
    if @user.save
      flash[:success] = 'User created successfully.'
      redirect_to users_path
    else
      flash[:error] = 'User not created.'
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = 'User deleted successfully.'
      redirect_to users_path
    else
      flash[:error] = 'User not deleted.'
      render :new
    end
  end

  private

  def object_params
    params.require(:user).permit(:email, :name, :last_name, :username,
                                 :password, :password_confirmation, :role_id,
                                 :customer_id)
  end
end

app/views/users/_form.html.slim
= simple_form_for(@user, html: {novalidate: false}) do |f|
  = f.input :email, placeholder: 'E.g. example@arters.com'
  = f.input :name, placeholder: 'E.g. Will'
  = f.input :last_name, placeholder: 'E.g. Smith'
  = f.input :username, placeholder: 'E.g. WillSmith68'
  = f.input :password, placeholder: '*********'
  = f.input :password_confirmation, placeholder: '*********'
  = f.association :role, include_blank: false
  = f.association :customer, include_blank: false
  div class="actions"
    = link_to users_path, class: "btn btn-md btn-primary pull-left" do
      | Back
    = f.submit class: "btn btn-md btn-primary pull-right"

app/views/users/_users_table.html.slim
table class="table table-striped datatable"
  thead
    tr
      th
        |Name
      th
        |Username
      th
        |Email
      th
        |Customer
      th
        |Role
      th
  tbody
    - @users.each do |user|
      - if user == current_user
        - next
      tr
        td
          = user.full_name
        td
          = user.username
        td
          = user.email
        td
          = user.customer.name
        td
          = user.role.name
        td style="width: 5%"
          = link_to user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" do 
            i.fa.fa-icon.fa-trash
          

app/views/users/index.html.slim
.row
  .col-md-6
    h1.page-title
      | Users
  .col-md-6
    span
      = link_to new_user_path, class: "btn btn-md btn-success pull-right", style: "margin-top: 15px;" do
        | New
.row
  .col-md-12
      = render partial: 'users_table'

app/views/users/new.html.slim
.row
  .col-md-6
    h1.page-title
      | New user
.row
  .col-md-12
    = render 'form'