config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  # Routes only without session
  scope constraints: ->(req) { req.session[:user_id].blank? } do
    get 'login', to: 'sessions#new', as: :new_login
    post 'login', to: 'sessions#create', as: :login
    resources :registration, only: [:new, :create]
  end

  # Routes only with session
  scope constraints: ->(req) { !req.session[:user_id].blank? } do
    # For every role
    get 'logout', to: 'sessions#destroy', as: :logout
    resources :purchase_orders

    # Just if you are an admin
    scope constraints: ->(req) { req.session[:role] == 'admin' } do
      resources :users, only: [:index, :new, :create, :destroy]
    end

    # Just if you are a regular_user
    scope constraints: ->(req) { req.session[:role] == 'regular_user' } do
    end


  end

  # For everyone
  # STATIC PAGES
  get 'contact_us', to: "welcome#contact_us", as: :contact_us
  resources :announcements
  resources :documents
  post 'create_document', to: 'documents#create', as: :create_document
  resources :reports do
    collection do
      get 'invoices'
      get 'deliveries'
      get 'product_information'
      get 'product_statistics'
      get 'purchase_orders'
      get 'product_summary'
      get 'date_statistics'
      get 'product_catalog'
      get 'product_documents'
      get 'invoices_json'
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def product_statistics
  end

  def product_summary
    product_statistics = current_customer.product_info(current_user)
    render json: { product_statistics: product_statistics}, status: 200
  end

  def purchase_orders
  end

  def deliveries
    @data = filter_customer(Order)
  end

  def invoices
    @data = filter_customer(Receivable)
  end

  def invoices_json
    invoices_json = filter_customer(Receivable)
    render json: { invoices_json: invoices_json }, status: 200
  end

  def date_statistics
    countOnTime = 0
    countDelayed = 0
    date_statistics = current_customer.dates_info(current_user)
    for i in date_statistics
      if i.to_date(i.promised_date) < i.to_date(i.last_ship_date)
        countDelayed += 1
      else
        countOnTime += 1
      end
    end
    render json: { onTime: countOnTime, delayed: countDelayed}, status:200
  end

  def product_catalog
    @products = current_customer.product_info(current_user)
  end

  def product_documents
    part = Part.find_by(description: params[:description])
    @documents = part.documents
  end
 
private
 
  def filter_customer(klass)
    return klass.all.paginate(page: params[:page], per_page:50) if current_user.admin?
    klass.where(customer_number: current_user.customer.number)
  end

  def filter_customerJSON(klass)
    return klass.all if current_user.admin?
    klass.where(customer_number: current_customer.number)
  end

  def product_information
  end
end

app/views/reports/product_catalog.html.slim
h1 Catálogo de productos
table.table.table-striped.datatable
  thead                     
    tr                          
      th Producto
      th Documentos
  tbody
    - @products.each do |product|   
      tr
        td = product[0]
        td = link_to 'Documentos', product_documents_reports_path(description: product[0]), class:'btn btn-primary btn-xs'

app/views/reports/product_documents.html.slim
h1 Documentos
.row
  .col-md-12
   = link_to 'Nuevo documento', new_document_path(description: params[:description]), class:'btn btn-primary'
.row style="margin-top: 15px"
  .col-md-12
    table.table.table-striped                     
      tr                          
        th Documento
        th Tipo de archivo
        th
        - if current_user.admin?
          th
      - @documents.each do |document|   
        tr
           td = document.description
           td = document.file_file_name.split(".").last
           td = link_to 'Descargar', document.file.url, class:'btn btn-primary btn-xs'
           - if current_user.admin?
              td
                = link_to 'Eliminar', document_path(document), method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: '¿Estas seguro?' }

app/views/reports/product_information.html.slim
h1
  |Product information

app/views/reports/purchase_orders.html.slim
h1
  |Purchase orders