config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  # Routes only without session
  scope constraints: ->(req) { req.session[:user_id].blank? } do
    get 'login', to: 'sessions#new', as: :new_login
    post 'login', to: 'sessions#create', as: :login
    resources :registration, only: [:new, :create]
  end

  # Routes only with session
  scope constraints: ->(req) { !req.session[:user_id].blank? } do
    # For every role
    get 'logout', to: 'sessions#destroy', as: :logout
    resources :purchase_orders

    # Just if you are an admin
    scope constraints: ->(req) { req.session[:role] == 'admin' } do
      resources :users, only: [:index, :new, :create, :destroy]
    end

    # Just if you are a regular_user
    scope constraints: ->(req) { req.session[:role] == 'regular_user' } do
    end


  end

  # For everyone
  # STATIC PAGES
  get 'contact_us', to: "welcome#contact_us", as: :contact_us
  resources :announcements
  resources :documents
  post 'create_document', to: 'documents#create', as: :create_document
  resources :reports do
    collection do
      get 'invoices'
      get 'deliveries'
      get 'product_information'
      get 'product_statistics'
      get 'purchase_orders'
      get 'product_summary'
      get 'date_statistics'
      get 'product_catalog'
      get 'product_documents'
      get 'invoices_json'
    end
  end
end

app/views/layouts/_login_modal.html.slim
div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  div class="modal-dialog" style="width: 400px;"
    div class="modal-content"
      = simple_form_for :sessions, url: login_path, html: { class: 'form-vertical' } do |f|
        div class="modal-header"
          button type="button" class="close" data-dismiss="modal" aria-label="Close"
            span aria-hidden="true"
              i class="fa fa-icon fa-times"
          h4 class="modal-title" id="myModalLabel" style="text-align: center;"
            |Login
        div class="modal-body"
          div class="row"
            div class="col-md-10 col-md-offset-1"
              = f.input :credential, input_html: { class: 'form-control' }, placeholder: 'Username or email', label: false
              = f.input :password, input_html: { class: 'form-control' }, class: 'form-control', placeholder: 'Password', label: false 
        div class="modal-footer"
          button type="button" class="btn btn-default" data-dismiss="modal"
            |Close
          = f.submit class: "btn btn-md btn-primary", value: 'Login'

app/views/layouts/_sweet_alerts.html.slim
- unless flash.empty?
  - [:success, :info, :danger, :error, :input].each do |condition| 
    - if flash[condition]
      javascript:
        $(function(){
          swal(
            { 
              title: "#{sweet_alert_title(condition)}", 
              text: "#{flash[condition]}", 
              type: "#{condition}" 
            }
          );
        })

app/views/layouts/admin.html.slim
doctype html
html
  head
    title
      | Gening
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    div id='wrapper'
      = render '/layouts/sweet_alerts'
      nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0"
        div class="navbar-header"
          button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
            span class="sr-only">
              | Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          a class="navbar-brand" href="index.html"
            | Gening

        ul class="nav navbar-top-links navbar-right"
          li class="dropdown"
            a class="dropdown-toggle" data-toggle="dropdown" href="#"
              i class="fa fa-user fa-fw"
              i class="fa fa-caret-down"
            ul class="dropdown-menu dropdown-user"
              li
                = link_to logout_path do 
                  | Logout
        div class="navbar-default sidebar" role="navigation"
          div class="sidebar-nav navbar-collapse"
            ul class="nav" id="side-menu"
              li
                = link_to announcements_path do
                  i class="fa fa-feed fa-fw"
                  | Anuncios
              li
                = link_to product_statistics_reports_path do
                  i class="fa fa-area-chart fa-fw"
                  | Estadística de productos
              li
                = link_to deliveries_reports_path do
                  i class="fa fa-truck fa-fw"
                  | Entregas
              li
                = link_to invoices_reports_path do
                  i class="fa fa-clipboard fa-fw"
                  | Facturas
              li
                = link_to product_catalog_reports_path do
                  i class="fa fa-info-circle fa-fw"
                  | Catálogo de productos
              li
                = link_to users_path do
                  i class="fa fa-user fa-fw"
                  | Usuarios
      #page-wrapper.container
        .col-md-11
          = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gening</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/nav.html.erb
nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0"
  div class="navbar-header"
    button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
      span class="sr-only">
        | Toggle navigation
      span class="icon-bar"
      span class="icon-bar"
      span class="icon-bar"
    a class="navbar-brand" href="index.html"
      | Gening

  ul class="nav navbar-top-links navbar-right"
    li class="dropdown"
      a class="dropdown-toggle" data-toggle="dropdown" href="#"
        i class="fa fa-user fa-fw"
        i class="fa fa-caret-down"
      ul class="dropdown-menu dropdown-user">
        li
          a href="#"
            i class="fa fa-user fa-fw" 
              | User Profile
        li
          a href="#"
            i class="fa fa-gear fa-fw"
              | Settings
        li class="divider"
        li
          a href="login.html"
            i class="fa fa-sign-out fa-fw"
              |Logout
  div class="navbar-default sidebar" role="navigation"
    div class="sidebar-nav navbar-collapse"
      ul class="nav" id="side-menu"
        li class="sidebar-search"
          div class="input-group custom-search-form"
            input type="text" class="form-control" placeholder="Search..."
            span class="input-group-btn"
            button class="btn btn-default" type="button"
              i class="fa fa-search"
        li
          a href="index.html"
            i class="fa fa-dashboard fa-fw"
            | Dashboard
        li
          a href="#"
            i class="fa fa-wrench fa-fw"
              | UI Elements
              span class="fa arrow"
          ul class="nav nav-second-level"
            li
              a href="#"
                | Panels and Wells
            li
              a href="#"
                | Buttons

app/views/layouts/not_logged.html.slim
doctype html
html
  head
    title
      | Gening
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    div id='wrapper'
      = render '/layouts/sweet_alerts'
      = render '/layouts/login_modal'
      nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0"
        div class="navbar-header"
          button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
            span class="sr-only">
              | Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          a class="navbar-brand" href="index.html"
            | Gening

        ul class="nav navbar-top-links navbar-right"
          li class="dropdown"
            a class="dropdown-toggle" data-toggle="dropdown" href="#"
              i class="fa fa-user fa-fw"
              i class="fa fa-caret-down"
            ul class="dropdown-menu dropdown-user"
              li
                a data-toggle="modal" data-target="#myModal"
                  | Login
        div class="navbar-default sidebar" role="navigation"
          div class="sidebar-nav navbar-collapse"
            ul class="nav" id="side-menu"
              li class="sidebar-search"
                div class="input-group custom-search-form"
                  input type="text" class="form-control" placeholder="Search..."
                  span class="input-group-btn"
                    button class="btn btn-default" type="button"
                      i class="fa fa-search"
      #page-wrapper.container
        .col-md-11
          = yield

app/views/layouts/regular_user.html.slim
doctype html
html
  head
    title
      | Gening
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    div id='wrapper'
      = render '/layouts/sweet_alerts'
      nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0"
        div class="navbar-header"
          button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
            span class="sr-only">
              | Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          a class="navbar-brand" href="index.html"
            | Gening

        ul class="nav navbar-top-links navbar-right"
          li class="dropdown"
            a class="dropdown-toggle" data-toggle="dropdown" href="#"
              i class="fa fa-user fa-fw"
              i class="fa fa-caret-down"
            ul class="dropdown-menu dropdown-user"
              li
                = link_to logout_path do 
                  | Logout
        div class="navbar-default sidebar" role="navigation"
          div class="sidebar-nav navbar-collapse"
            ul class="nav" id="side-menu"
              li
                = link_to announcements_path do
                  i class="fa fa-feed fa-fw"
                  | Anuncios
              li
                = link_to product_statistics_reports_path do
                  i class="fa fa-area-chart fa-fw"
                  | Estadística de productos
              li
                = link_to deliveries_reports_path do
                  i class="fa fa-truck fa-fw"
                  | Entregas
              li
                = link_to invoices_reports_path do
                  i class="fa fa-clipboard fa-fw"
                  | Facturas
              li
                = link_to product_catalog_reports_path do
                  i class="fa fa-info-circle fa-fw"
                  | Catálogo de productos
      #page-wrapper.container
        .col-md-11
          = yield